### ISSUE TITLE
print not written for -- twkde.markovian

### ISSUE THREAD

**Issue by siddharthgarg89** [cmu-delphi/epiforecast-R#2]
Hello Delphi Team,

I was trying to use the function twde.markovian in the epiforecast package to predict and subsequently the flu predictions in RStudio. However, this function does not have the print capabilities yet. The error message while trying to do so is - **_Error in print.sim(x) : print not written for -- twkde.markovian  -- yet!_**

Although, the plot function works well for plotting the flu trajectory. Could you please add the print capabilities to the package?

**Comment by brookslogan** [comment]
Sure!  Thanks for pointing this out.  This issue should be addressed by commit b9ef9111395ca35e52cc1d73b0aab273a25640ca.

**Comment by siddharthgarg89** [comment]
This is working now, Logan. Thank you so much! :)
