### ISSUE TITLE
Error in twkde.markovian.sim function

### ISSUE THREAD

**Issue by siddharthgarg89** [cmu-delphi/epiforecast-R#3]
I am trying to run the sample code provided in the documentation for the epiforecast package for the twkde.markovian.sim function. However, when I do so, I get the error - **_Error in twkde.markovian.sim(dat, new.dat, 2.1, n.sims = 100) : 
  unused argument (n.sims = 100)_**

the code used is per the epiforecast documentation on page 34

Requesting you to please look into this.

**Comment by lcbrooks** [comment]
The n.sims parameter has been renamed to max.n.sims.  The manual pdf was out of date; it has been regenerated in commit e80b438b44d5ea19615528865afb7dc8f44381c4.

**Comment by lcbrooks** [comment]
Thanks for pointing this out.  I believe the above commit should resolve this documentation issue; marking as closed.

**Comment by siddharthgarg89** [comment]
Hello Logan,

Thank you for the quick turnaround. This seems to be working now. However, there is a another error in the function now. I have reported a separate issue for that.

Thanks
