### ISSUE TITLE
Clarification Required: twkde.markovian.sim function

### ISSUE THREAD

**Issue by siddharthgarg89** [cmu-delphi/epiforecast-R#4]
Hello Delphi Team,

I was referring to the updated documentation for the epiforecast package and had a few queries regarding the twkde.markovian.sim function -

1. When I run the code - **_sim = twkde.markovian.sim(dat, new.dat, baseline=2.1, max.n.sims=100)_**, I get an error message that says - **_Error in twkde.markovian.sim(dat, new.dat, baseline = 2.1, max.n.sims = 100) : unused argument (new.dat)_**

2. The code works fine w/o any error when I use - sim = twkde.markovian.sim(full.dat, baseline=2.1, max.n.sims=100)

Could you please help us out in understanding if the second piece of code is apt and the first one should be discarded or if the first one will work as well post some changes to epiforecast package or its documentation?

**Comment by brookslogan** [comment]
Thanks for pointing this out; looks like the docstrings themselves are not up to date, not just the manual pdf.

This example works by substituting that call with
`twkde.markovian.sim(full.dat, baseline=2.1, max.n.sims=100)`
--- `full.dat` is defined earlier in the example.  See also [demo/demo.R](https://github.com/cmu-delphi/epiforecast-R/blob/master/demo/demo.R) for more examples of usage.

**Comment by siddharthgarg89** [comment]
Thank you, once again, for the clarification, Logan. Would be possible to have the docstrings updated as well? I understand that this may be an overhead for the Delphi team but it will help us a lot.

**Comment by brookslogan** [comment]
Sure, the docstrings have been updated to reflect this change in commit 7439cb7fb9c7c3261d5508e699cb2aa9c78d69a0.  Additionally, the documentation has been expanded and cleaned up a bit in other areas.  Please let me know if you see any additional issues.
