### ISSUE TITLE
forecasts with negative values

### ISSUE THREAD

**Issue by eampo** [cmu-delphi/epiforecast-R#5]
Hello,

Thank you for sharing this tool! I encountered an issue recently where I had negative values for predictions.  I'm currently rounding these values up to zero, but just wanted to make sure that this is best practice.

Elijah

**Comment by brookslogan** [comment]
Some or all of the algorithms were written to apply to potentially negative data (although we've only applied them to >=0 data).  We also post-process the forecasts to replace negative values in the simulated trajectories with 0's.  I am not sure what the best practice would be, but this sounds reasonable/practical.

(Alternate approach: we could imagine, in methods like delta density, thresholding values as we simulate each time step in sequence, which should reduce the size and frequency of extended <=0 sections, but this may lead to an undesired positive bias in later values in cases where the trajectories rise >0 sometime.)
